/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.*;
/**
 *
 * @author marcomatarese
 */

public class MainWindow extends JFrame {

    /**
     * Creates new form JFrame
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        mainPanel.getRootPane().setDefaultButton(addClausButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        instructionLabel = new javax.swing.JLabel();
        addClausTextField = new javax.swing.JTextField();
        applyDPPButton = new javax.swing.JButton();
        resultsLabel = new javax.swing.JLabel();
        deleteClausButton = new javax.swing.JButton();
        formulaLabel = new javax.swing.JLabel();
        addClausButton = new javax.swing.JButton();
        ClauseLabel = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        showManualMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setText("<html>Welcome to <b>DPP Solver</b>:<br>the programm that emulates the <b>Davis-Putnam</b> procedure!</html>");

        instructionLabel.setText("<html><b>Instructions:</b><br>- Insert a clause at a time using the CNF notation<br>- For insert the clause {A, -A} type 'A,-A' or 'A-A'.<br>- Click Add Clause.<br>- You can see your formula below.<br>- When all the clauses have been inserted click Apply DPP.<br>- The results are shown below.</html>");

        addClausTextField.setText("A-A");

        applyDPPButton.setText("Apply DPP");
        applyDPPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyDPPButtonActionPerformed(evt);
            }
        });

        resultsLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        resultsLabel.setText("Results: ");

        deleteClausButton.setText("Delete");
        deleteClausButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClausButtonActionPerformed(evt);
            }
        });

        formulaLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        formulaLabel.setText("Your Formula = {}");

        addClausButton.setText("Add");
        addClausButton.setSize(new java.awt.Dimension(97, 29));
        addClausButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClausButtonActionPerformed(evt);
            }
        });

        ClauseLabel.setText("Next Clause:");

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(ClauseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addClausTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(welcomeLabel)
                    .addComponent(instructionLabel)
                    .addComponent(formulaLabel)
                    .addComponent(resultsLabel)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(addClausButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteClausButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applyDPPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instructionLabel)
                .addGap(34, 34, 34)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClausTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClauseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteClausButton)
                    .addComponent(addClausButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formulaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyDPPButton)
                    .addComponent(newButton))
                .addContainerGap())
        );

        helpMenu.setText("Help");

        showManualMenuItem.setText("Show Manual");
        showManualMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showManualMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(showManualMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addClausButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClausButtonActionPerformed
        // TODO add your handling code here:
        Clausola cl = new Clausola();
        String s = null, list = addClausTextField.getText(), supp = null;

        //Visive effects.
        addClausTextField.setText("");

        for(int i = 0; i < list.length(); i++){
            s = String.valueOf(list.charAt(i));
            if(s.equals(" ") || s.equals(",")) continue;
            //The Letterale is negate.
            if(s.equals("-")){
                s = String.valueOf(list.charAt(++i));
                cl.listOfL.add(new Letterale(s, true));
            }
            //The Letterale is not negate.
            else{
                cl.listOfL.add(new Letterale(s, false));
            }
        }

        if(Control.form.listOfC.add(cl)){
            //Visive effects.
            supp = formulaLabel.getText().substring(0, formulaLabel.getText().length() - 1);
            formulaLabel.setText(supp.concat("{" + list) + "}}");
        }
    }//GEN-LAST:event_addClausButtonActionPerformed

    private void deleteClausButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClausButtonActionPerformed
        // TODO add your handling code here:
        addClausTextField.setText("");
    }//GEN-LAST:event_deleteClausButtonActionPerformed

    private void applyDPPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyDPPButtonActionPerformed
        // TODO add your handling code here:
        //Calls the program's kernel.
        Control.goToDpp();
        //The controll on the last Clausola.
        boolean cond = Control.form.ultimateControl();
        System.out.println("Formula: " + Control.form);
        //Clean all the used memory.
        Control.cleanAll();

        //Visual effects.
        resultsLabel.setText("Results:");

        if(cond)
            resultsLabel.setText(resultsLabel.getText().concat(" your formula is satisfiable!"));
        else
            resultsLabel.setText(resultsLabel.getText().concat(" your formula is unsatisfiable!"));
    }//GEN-LAST:event_applyDPPButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
        //Function that cleans the memory.
        Control.cleanAll();
        
        //Visual effetcs.
        formulaLabel.setText("Your Formula = {}");
        resultsLabel.setText("Results:");
    }//GEN-LAST:event_newButtonActionPerformed

    private void showManualMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showManualMenuItemActionPerformed
        // TODO add your handling code here:
        String path = "C:\\Program Files (x86)\\DPPSolver\\Manual.pdf";
        if (Desktop.isDesktopSupported()) {
        try {
            File myFile = new File(path);
            Desktop.getDesktop().open(myFile);
        }catch (IOException ex) {
            
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, "The file not exists!", "Inane warning", JOptionPane.WARNING_MESSAGE);
        }
}
    }//GEN-LAST:event_showManualMenuItemActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception e){System.out.println("Run-time Exception was caught! LookAndFeel: " + e.getMessage());}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClauseLabel;
    private javax.swing.JButton addClausButton;
    private javax.swing.JTextField addClausTextField;
    private javax.swing.JButton applyDPPButton;
    private javax.swing.JButton deleteClausButton;
    private javax.swing.JLabel formulaLabel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newButton;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JMenuItem showManualMenuItem;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
